[package]
name = "vkrunner"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A shader testing tool for Vulkan"
repository = "https://gitlab.freedesktop.org/mesa/vkrunner/"
default-run = "vkrunner"

[lib]
path = "vkrunner/lib.rs"

[build-dependencies]
bindgen = "0.66.1"
